-- // inserts nova tela consultar os
-- Migration SQL that makes the change goes here.

INSERT INTO SEGURANCA.FUNCIONALIDADE (
	FNCD_ID,
	MODU_ID,
	FNCD_DSFUNCIONALIDADE,
	FNCD_TMULTIMAALTERACAO,
	FNCD_DSCAMINHOMENU,
	FNCD_DSCAMINHOURL,
	FNCD_ICPONTOENTRADA,
	FNCD_DSABREVIADO,
	FNCD_NNORDEMMENU,
	FNCD_ICNOVAJANELA,
	FNCD_ICOLAP,
	FNCG_ID,
	URL)
VALUES (
	NEXTVAL('seguranca.seq_funcionalidade'), 
	6, 'Consultar Ordens Servico', 
	NOW(), 
	NULL, 
	'http://portalgsan.cosanpa.pa.gov.br/ordem_servicos', 
	2, 
	'CONOS', 
	100, 
	2,
	2,
	51,
	'http://portalgsan.cosanpa.pa.gov.br/ordem_servicos'
);

INSERT INTO SEGURANCA.OPERACAO VALUES (
	NEXTVAL('seguranca.seq_operacao'),
	(SELECT FNCD_ID FROM SEGURANCA.FUNCIONALIDADE WHERE FNCD_DSFUNCIONALIDADE like 'Consultar Ordens Servico'),
	'Consultar Ordens Servico',
	'CONOS',
	NULL,
	NOW(),
	NULL,
	NULL,
	6,
	NULL,
	2
);


INSERT INTO SEGURANCA.GRUPO_FUNC_OPERACAO VALUES (
	1,
	(SELECT OPER_ID FROM SEGURANCA.OPERACAO WHERE OPER_DSOPERACAO like 'Consultar Ordens Servico'),
	(SELECT FNCD_ID FROM SEGURANCA.FUNCIONALIDADE WHERE FNCD_DSFUNCIONALIDADE like 'Consultar Ordens Servico'),
	NOW()
);


-- //@UNDO
-- SQL to undo the change goes here.

DELETE FROM SEGURANCA.GRUPO_FUNC_OPERACAO WHERE FNCD_ID IN (SELECT FNCD_ID FROM SEGURANCA.FUNCIONALIDADE WHERE FNCD_DSFUNCIONALIDADE like 'Consultar Ordens Servico');
DELETE FROM SEGURANCA.OPERACAO WHERE OPER_ID IN (SELECT OPER_ID FROM SEGURANCA.OPERACAO WHERE OPER_DSOPERACAO like 'Consultar Ordens Servico');
DELETE FROM SEGURANCA.FUNCIONALIDADE WHERE FNCD_ID IN (SELECT FNCD_ID FROM SEGURANCA.FUNCIONALIDADE WHERE FNCD_DSFUNCIONALIDADE like 'Consultar Ordens Servico');
